development:
  adapter: mysql
  database: azmt_development

test:
  adapter: mysql
  database: azmt_test

production:
  adapter: mysql
  database: azmt_en21_org
  username: azmt
  password: azmtehnois2002.1
  socket: /var/run/mysqld/mysqld.sock