development:
  adapter: mysql
  database: azmt_development
  username: root
  password: admmysql

test:
  adapter: mysql
  database: azmt_test
  username: root
  password: admmysql

production:
  adapter: mysql
  database: azmt_en21_org
  username: azmt
  password: azmtehnois2002.1
  socket: /var/run/mysqld/mysqld.sock